language: go

before_install:
  - openssl aes-256-cbc -K $encrypted_350a37d464b5_key -iv $encrypted_350a37d464b5_iv -in pedafy-251c5ecfe2ec.json.enc -out pedafy-251c5ecfe2ec.json -d

script:
  - go build -o server
  - go clean

# current API version: 1.0.0
deploy:
  provider: gae
  keyfile: pedafy-251c5ecfe2ec.json
  project: pedafy
  version: v1
  no_promote: true
  no_stop_previous_version: true
  on: master
