language: go

before_install:
  - openssl aes-256-cbc -K $encrypted_350a37d464b5_key -iv $encrypted_350a37d464b5_iv -in ./keys/pedafy-251c5ecfe2ec.json.enc -out pedafy-251c5ecfe2ec.json -d

script:
  - go build -o server ./src/app
  - go vet ./src/api ./src/api/apiv1 ./src/api/layer ./src/app ./src/database ./src/database/dblayer ./src/database/dbv1 ./src/datastore ./src/version
  - go clean

# current version: 1
deploy:
  provider: gae
  keyfile: pedafy-251c5ecfe2ec.json
  project: pedafy
  config: ./src/app/app.yaml
  on: master
